base_title: 大根的博客
# base_url: http://0.0.0.0:4000
# base_url: http://192.168.199.129:4000
base_url: http://dragonwong.github.io/blog
paginate: 8
paginate_path: "/page/:num"
highlighter: pygments

# 重庆夜景
# cover_l: http://pic.yupoo.com/dragonwong/DMt9l8Yd/dChvA.jpg
# cover_s: http://pic.yupoo.com/dragonwong/DMt9l8Yd/medish.jpg

# 承德避暑山庄
cover_l: http://pic.yupoo.com/dragonwong/EJH1t8AO/aEPcA.jpg
cover_s: http://pic.yupoo.com/dragonwong/EJH1t8AO/medish.jpg

gems:
  - jemoji